.TH SLICER "May 2023" "1.0" "File Manipulation Application"

.SH NAME
slicer \- File Manipulation Application

.SH SYNOPSIS
.B slicer
SOURCE ITERATION

.SH DESCRIPTION
Slicer helps you duplicate files and shuffle contents of the file on each duplicated file.

.SH AUTHOR
Written by Sam B. Morris <divinestylus@gmail.com> and Varma Cephas <varmac231@gmail.com>.

.SH COPYRIGHT
Copyright ©2023 Sam B. Morris and Varma Cephas.
This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.

.SH SEE ALSO
Full documentation on <https://github.com/divinestylus/slicer-bash-application#readme>.

.SH BUGS
Report bugs here: <https:/https://github.com/divinestylus/slicer-bash-application/issues>. Please include as much relevant information as possible.



